from app.services.llm.base import ResumeGenerationResult


class MockResumeLLMClient:
    def generate_resume_artifacts(
        self,
        *,
        profile: str,
        job_description: str,
    ) -> ResumeGenerationResult:
        keywords = self._extract_keywords(job_description)
        profile_excerpt = profile.strip()
        job_excerpt = job_description.strip()

        return ResumeGenerationResult(
            keywords=keywords,
            review_summary="Mock review completed. The draft aligns the profile with the target role.",
            final_cover_letter=(
                "This is a mock cover letter generated by the Resume Agent Platform. "
                f"Candidate profile summary: {profile_excerpt}. "
                f"Target job summary: {job_excerpt}."
            ),
        )

    def _extract_keywords(self, job_description: str) -> list[str]:
        normalized = job_description.replace(",", " ").replace(".", " ").split()
        unique_words: list[str] = []

        for word in normalized:
            token = word.strip().lower()
            if len(token) < 4:
                continue
            if token in unique_words:
                continue
            unique_words.append(token)
            if len(unique_words) == 5:
                break

        if unique_words:
            return unique_words

        return ["mock", "resume", "agent"]
